// src/components/atoms/title.tsx
import clsx from "clsx";

const weights = {
  bold: "font-bold",
  semibold: "font-semibold",
  medium: "font-medium",
  normal: "font-normal",
} as const;

const colors = {
  black: "text-neutral-900",
  primary: "text-brand-950",
  secondary: "text-sgreen",
  muted: "text-neutral-400",
  gradientPrimary:
    "bg-gradient-to-br from-brand-400 to-brand-900 dark:from-brand-100 dark:to-brand-300 inline-block text-transparent bg-clip-text",
  destructive: "text-rose-700",
};

function Title({
  title,
  size,
  weight,
  capitalize,
  color,
  id,
}: {
  title: string;
  capitalize?: boolean;
  size?: "h1" | "h2" | "h3" | "h4" | "h5";
  weight?: keyof typeof weights;
  color?: keyof typeof colors;
  id?: string;
}) {
  switch (size) {
    case "h1":
      return (
        <h1
          id={id}
          className={clsx(
            "font-serif text-4xl md:text-5xl",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h1>
      );
    case "h2":
      return (
        <h2
          id={id}
          className={clsx(
            "font-serif text-3xl lg:text-4xl",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h2>
      );
    case "h3":
      return (
        <h3
          id={id}
          className={clsx(
            "font-serif text-xl lg:text-2xl",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h3>
      );
    case "h4":
      return (
        <h4
          id={id}
          className={clsx(
            "font-serif text-lg lg:text-xl",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h4>
      );
    case "h5":
      return (
        <h5
          id={id}
          className={clsx(
            "font-serif text-base lg:text-lg",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h5>
      );
    default:
      return (
        <h1
          id={id}
          className={clsx(
            "font-serif text-4xl md:text-5xl",
            colors[color ?? "secondary"],
            weights[weight ?? "semibold"],
            capitalize && "capitalize",
          )}
        >
          {title}
        </h1>
      );
  }
}

export default Title;

// src/lib/components/title.svelte
<script lang="ts">
    import clsx from "clsx";

    type TitleSize = "h1" | "h2" | "h3" | "h4";
    type TitleFontWeight = "bold" | "semibold" | "normal" | "medium";

    const colors = {
        white: "text-indigo-50 dark:text-indigo-950",
		black: "inline-block bg-gradient-to-r from-gray-500 to-slate-900 bg-clip-text font-semibold text-transparent",
        primary: "text-indigo-600 dark:text-indigo-50",
    };

    const weights = {
        bold: "font-bold",
        semibold: "font-semibold",
        medium: "font-medium",
        normal: "font-normal",
    } as const;

    export let text: string = "";
    export let size: TitleSize = "h2";
    export let weight: TitleFontWeight = "semibold";
    export let capitalize: boolean = true;
    export let color: keyof typeof colors = "black";
</script>

{#if size == "h1"}
    <h1
        class={clsx(
            "w-max text-4xl lg:text-5xl",
            weights[weight ?? "bold"],
            capitalize && "capitalize",
            colors[color],
        )}
    >
        {text}
    </h1>
{:else if size == "h2"}
    <h2
        class={clsx(
            "w-max text-3xl lg:text-4xl",
            weights[weight ?? "bold"],
            capitalize && "capitalize",
            colors[color],
        )}
    >
        {text}
    </h2>
{:else if size == "h3"}
    <h3
        class={clsx(
            "w-max text-2xl lg:text-3xl",
            weights[weight ?? "bold"],
            capitalize && "capitalize",
            colors[color],
        )}
    >
        {text}
    </h3>
{:else if size == "h4"}
    <h4
        class={clsx(
            "w-max text-xl lg:text-2xl",
            weights[weight ?? "bold"],
            capitalize && "capitalize",
            colors[color],
        )}
    >
        {text}
    </h4>
{/if}
